In [1]:
import numpy as np
import random #to generate random array
from sklearn.datasets import load_diabetes
from sklearn.linear_model import SGDRegressor
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [2]:
X,y=load_diabetes(return_X_y=True)

In [3]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=13)

In [4]:
SGD=SGDRegressor( loss='squared_error',max_iter=1000, shuffle=True)

In [5]:
SGD.fit(X_train,y_train)

C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:1503: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


SGDRegressor()

In [6]:
SGD.intercept_

array([150.24478839])

In [7]:
ypred=SGD.predict(X_test)

In [8]:
r2_score(y_test,ypred)

0.3632001362149393

In [152]:
class mbsgdregressor:
    def __init__(self,lr,epoche,batch_size):
        self.lr=lr
        self.batch_size=batch_size
        self.epoche=epoche
    def fit(self,X_train,y_train):
        intercept_=0
        coeff_=np.ones(X_train.shape[1])
        for i in range(self.epoche):
            for j in range(int(X_train.shape[0]/self.batch_size)):
                idx=random.sample(range(X_train.shape[0]),self.batch_size)
                yhat=intercept_+np.dot(X_train[idx],coeff_)
                loss1=-2*np.mean(y_train[idx]-yhat)
                intercept_=intercept_-self.lr*loss1
                loss2=-2*np.dot((y_train[idx]-yhat),X_train[idx])/self.batch_size
                coeff_=coeff_-self.lr*loss2
        self.intercept_=intercept_
        self.coeff_=coeff_
    def predict(self,X_test):
        return self.intercept_+np.dot(X_test,self.coeff_)

In [220]:
mbsgd=mbsgdregressor(0.1,50,10)

In [221]:
mbsgd.fit(X_train,y_train)

In [222]:
mbsgd.intercept_

153.64665255621642

In [223]:
mbsgd.coeff_

array([  36.14017882,  -82.70642037,  379.32237187,  242.58705265,
         19.92989927,  -20.09477776, -174.48974106,  143.54303944,
        292.1149131 ,  163.17817824])

In [224]:
ypred=mbsgd.predict(X_test)

In [225]:
r2_score(y_test,ypred)

0.3925365511026776

In [85]:
int(X_train.shape[0]/mbsgd.batch_size)

35

In [88]:
idx=random.sample(range(X_train.shape[0]),mbsgd.batch_size)
X_train[idx]


array([[ 0.03444337,  0.05068012, -0.00189471, -0.01255635,  0.03833367,
         0.01371725,  0.0780932 , -0.03949338,  0.00455189, -0.09634616],
       [-0.00551455,  0.05068012, -0.01159501,  0.01154374, -0.02220825,
        -0.01540556, -0.02131102, -0.00259226,  0.0110081 ,  0.06933812],
       [-0.02004471, -0.04464164, -0.0547075 , -0.0538708 , -0.06623874,
        -0.05736745,  0.01182372, -0.03949338, -0.07408887, -0.0052198 ],
       [ 0.11072668,  0.05068012,  0.00672779,  0.0287581 , -0.02771206,
        -0.0072637 , -0.04708248,  0.03430886,  0.00200784,  0.07762233],
       [ 0.0090156 ,  0.05068012,  0.01858372,  0.03908671,  0.01769438,
         0.01058576,  0.019187  , -0.00259226,  0.01630495, -0.01764613],
       [-0.03094232, -0.04464164,  0.00564998, -0.00911348,  0.01907033,
         0.00682798,  0.07441156, -0.03949338, -0.04118039, -0.04249877],
       [ 0.01991321, -0.04464164,  0.00457217,  0.04597245, -0.01808039,
        -0.05454912,  0.06336665, -0.03949338