In [158]:
import numpy as np
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
import pandas as pd

In [159]:
X,y=load_diabetes(return_X_y=True)
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [160]:
X=np.insert(X,0,1,axis=1)
X[3]

array([ 1.        , -0.08906294, -0.04464164, -0.01159501, -0.03665645,
        0.01219057,  0.02499059, -0.03603757,  0.03430886,  0.02269202,
       -0.00936191])

In [161]:
X.shape

(442, 11)

In [162]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [163]:
print(X_train.shape,
X_test.shape)

(353, 11) (89, 11)


In [164]:
class MultipleRegression:
    def __init__(self,x,y):
        self.X_train=x
        self.y_train=y
        
    def fit(self):
        b=np.dot(np.linalg.inv(np.dot(self.X_train.T,self.X_train)),np.dot(self.X_train.T,self.y_train))
        self.b=b
    def predict(self,x):
        self.x=x
        return  np.dot(self.x,self.b)
    

In [165]:
lr=MultipleRegression(X_train,y_train)
lr.fit()

In [166]:
lr.b

array([ 151.88334521,   -9.16088483, -205.46225988,  516.68462383,
        340.62734108, -895.54360867,  561.21453306,  153.88478595,
        126.73431596,  861.12139955,   52.41982836])

In [167]:
lr.predict(X_test)

array([154.1235067 , 204.81721599, 124.92988001, 106.09339576,
       258.53035681, 256.32953702, 118.75258786, 119.52147402,
       101.50717468, 190.54137158, 141.70360267, 172.51631204,
       174.34089304, 134.81184017, 294.13950798,  94.11403289,
       211.97052873, 156.49984762, 134.20709632, 119.62534726,
       148.88045343, 165.00378118, 151.09977307, 176.03719872,
       133.27651748, 221.29531227, 197.17482787,  96.15923158,
        50.26531577, 230.48342249, 242.06266394, 114.1153262 ,
        67.0785352 ,  94.53179042, 201.21593262, 167.05306138,
       159.87838519, 192.78601513, 114.49291816, 233.4825497 ,
       140.82309666, 121.06814332, 192.27431013, 191.13157307,
       179.1698153 , 148.35140027, 163.47610288, 276.81203359,
       100.17813072, 164.11265163, 255.81074398, 136.94979051,
       152.37507828, 107.92662528, 194.21661635,  77.35015426,
       118.50951725,  68.38527563, 154.29094022, 162.48905632,
       168.36590928, 156.8764705 ,  97.13958436, 238.17

In [168]:
y_test

array([ 73., 233.,  97., 111., 277., 341.,  64.,  68.,  65., 178., 142.,
        77., 244., 115., 258.,  87., 220.,  86.,  74., 132., 136., 220.,
        91., 235., 148., 317., 131.,  84.,  65., 217., 306.,  79., 158.,
        54., 123., 174., 237., 212., 179., 281., 187., 200.,  68., 163.,
       141., 202., 178., 242.,  47., 131., 243., 142., 200.,  89., 232.,
        55., 253., 128., 104., 184., 110., 198.,  81., 195., 150.,  63.,
       151., 233., 178.,  84., 237., 109., 131., 252., 200., 160., 200.,
        51., 111.,  77., 201.,  88.,  78., 243., 268.,  55., 270., 288.,
        91.])

In [169]:
from sklearn.linear_model import LinearRegression

In [170]:
lor=LinearRegression()
lor.fit(X_train,y_train)

LinearRegression()

In [171]:
lor.predict(X_test)

array([154.1235067 , 204.81721599, 124.92988001, 106.09339576,
       258.53035681, 256.32953702, 118.75258786, 119.52147402,
       101.50717468, 190.54137158, 141.70360267, 172.51631204,
       174.34089304, 134.81184017, 294.13950798,  94.11403289,
       211.97052873, 156.49984762, 134.20709632, 119.62534726,
       148.88045343, 165.00378118, 151.09977307, 176.03719872,
       133.27651748, 221.29531227, 197.17482787,  96.15923158,
        50.26531577, 230.48342249, 242.06266394, 114.1153262 ,
        67.0785352 ,  94.53179042, 201.21593262, 167.05306138,
       159.87838519, 192.78601513, 114.49291816, 233.4825497 ,
       140.82309666, 121.06814332, 192.27431013, 191.13157307,
       179.1698153 , 148.35140027, 163.47610288, 276.81203359,
       100.17813072, 164.11265163, 255.81074398, 136.94979051,
       152.37507828, 107.92662528, 194.21661635,  77.35015426,
       118.50951725,  68.38527563, 154.29094022, 162.48905632,
       168.36590928, 156.8764705 ,  97.13958436, 238.17

In [172]:
lor.coef_

array([   0.        ,   -9.16088483, -205.46225988,  516.68462383,
        340.62734108, -895.54360867,  561.21453306,  153.88478595,
        126.73431596,  861.12139955,   52.41982836])

In [173]:
lr.b

array([ 151.88334521,   -9.16088483, -205.46225988,  516.68462383,
        340.62734108, -895.54360867,  561.21453306,  153.88478595,
        126.73431596,  861.12139955,   52.41982836])