In [4]:
import numpy as np
from sklearn.datasets import load_diabetes
from sklearn.linear_model import SGDRegressor
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [2]:
X,y=load_diabetes(return_X_y=True)

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=13)

In [19]:
SGD=SGDRegressor( loss='squared_error',max_iter=1000, shuffle=True)

In [20]:
SGD.fit(X_train,y_train)

C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:1503: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


SGDRegressor()

In [35]:
SGD.intercept_

array([150.27070398])

In [21]:
ypred=SGD.predict(X_test)

In [22]:
r2_score(y_test,ypred)

0.3634353558789384

In [93]:
class sgdregressor:
    def __init__(self,lr,epoche):
        self.lr=lr
        self.epoche=epoche
    def fit(self,X_train,y_train):
        intercept_=0
        coeff_=np.ones(X_train.shape[1])
        for i in range(self.epoche):
            for j in range (X_train.shape[0]):
                ref=np.random.randint(0,X_train.shape[0])
                yhat=intercept_+np.dot(coeff_,X_train[ref])
                dloss=-2*(y_train[ref]-yhat)
                intercept_=intercept_-self.lr*dloss
                
                dloss1=-2*np.dot((y_train[ref]-yhat),X_train[ref])
                coeff_=coeff_-self.lr*dloss1
        self.intercept_=intercept_
        self.coeff_=coeff_

       
    def predict(self,X_test):
        return self.intercept_+np.dot(X_test,self.coeff_)

In [94]:
sgd=sgdregressor(0.01,100)

In [95]:
sgd.fit(X_train,y_train)

In [96]:
sgd.intercept_

151.09390566081413

In [97]:
sgd.coeff_

array([   5.84892949, -170.72188345,  503.08431854,  290.91298029,
        -26.07377846,  -89.24945903, -203.60878943,  132.98660124,
        376.6229966 ,  165.74843389])

In [98]:
r2_score(y_test,sgd.predict(X_test))

0.3790215300977462

In [56]:
SGD.coef_

array([  42.85186899,  -33.8342236 ,  273.69779561,  184.0754043 ,
         44.94267516,   20.46456779, -140.93476489,  134.21574827,
        221.84086164,  143.00904431])